### PR TITLE
Add MIT license and Crown copyright notice

### PR DESCRIPTION
**Pull request by smellems**

### CODE REVIEW

**Comment by bartjkdp** [comment]
Hi Sebastian, we have some other LICENSE options as well:

- EUPL1.2
- Apache2

What are your opinions about these? Is there a reason we would need the Crown copyright notice?

**Comment by bartjkdp** [comment]
Think MIT is just fine, but wonder how we would manage the copyright. Obviously the Pleio developers are not subject to the Crown copyright. Also regarding to contributing to our project, what do you guys think of [DCO](https://about.gitlab.com/2017/11/01/gitlab-switches-to-dco-license/)?

**Comment by smellems** [comment]
My first choice was [AGPL](https://github.com/smellems/backend2/commit/c2a2e8e0fe7c61170d1b55714fe326d6319ace12), but we want a less restrictive (reciprocal) approach.  

We share the copyright.  We need to have the Crown copyright there and you need to add your own copyright holder.

Something like:
```
Copyright (c) 2017 the following
    Crown Copyright, Government of Canada
    Pleio?
```

**Comment by bartjkdp** [comment]
Great, we are settled then. I will add it then. Total would be:

````
Copyright (c) 2017 the following
    Crown Copyright, Government of Canada
    Stichting Pleio, The Netherlands
````

**Pull request merged**
